version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  jobs:
    post_create_environment:
      - poetry config virtualenvs.create false
    post_install:
      - poetry install

conda:
  environment: environment.yml

sphinx:
  configuration: docs/conf.py