_target_: endogen.config.GlobalSimConfig
input_data: data/cy_data_static_test.csv
time_var: year
unit_var: gwcode
nsim: 1000
end: 2100
include_past_n: 30
vars: ['gdppc', 'grwth', 'population', 'intensity_level', 'v2x_libdem', 'psecprop', 'rgdp']