_target_: endogen.config.InputModel
stage: writing
output_var: grwth
input_vars: [gdppc_l1, grwth_rm4_l1, intensity_level_hlm8_l1, psecprop_l1]
model: 
  _target_ : mlforecast.MLForecast
  models:
    - _target_: sklearn.linear_model.LinearRegression
    - _target_: sklearn.ensemble.RandomForestRegressor
  freq: 1
  num_threads: 4
lags:
  - _target_: endogen.config.Lags
    num_lag: 1
    input_vars: [gdppc, grwth_rm4, intensity_level_hlm8, psecprop]
rolling:
  - _target_: endogen.config.Rolling
    window: 4
    funs: [mean]
    input_vars: [grwth]
  - _target_: endogen.config.Rolling
    window: 8
    window_type: halflife
    funs: [mean]
    input_vars: [intensity_level]
transforms:
  - _target_: endogen.config.Transform
    output_var: gdppc
    input_vars: [gdppc_l1, grwth]
    formula: np.add(gdppc_l1, gdppc_l1*grwth)
    after_forecast: True 
